### ISSUE TITLE
PreferenceKeys 클래스 변환( 따라서 해 봅니다 )

### ISSUE THREAD

**Issue by patternoid** [kotlin-korea/Minimal-Todo#9]
먼저 하신 분이 계시기도 하고, 
이슈 등록 -> 브랜치 생성 -> 코틀린 변환작업 -> 커밋 -> PR 까지 빠르게 경험하고 싶었습니다. 
또한 이 클래스가 짧아서 시험 삼아서 해보기 좋다고 판단했습니다.

**Comment by ganadist** [comment]
그런데 이슈는 합치는게 좋지 않을까요?

**Comment by ganadist** [comment]
#7 와 중복됩니다.
